[project]
name = "douyou-assistant"
version = "0.1.0"
description = "抖音全能助手 - 支持多账号的抖音视频下载和上传工具"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests",
    "playwright",
    "rich",
    "browser-cookie3",
    "customtkinter>=5.2.2",
]
