name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            platform: windows
            ext: .exe
          - os: macos-latest
            platform: macos
            ext: ''

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        # 卸载可能存在的过时pathlib包
        pip uninstall pathlib -y || true
        pip install -r requirements.txt
        pip install pyinstaller pillow

    - name: Install Playwright browsers
      shell: bash
      run: |
        playwright install chromium
        playwright install-deps

    - name: Clean Qt duplicates before build
      run: rm -rf dist build && python -m pip uninstall -y PySide6-Essentials 2>/dev/null || true
    
    - name: Upgrade PyInstaller and clean cache
      run: |
        python -m pip install -U "pyinstaller>=6.6,<7"
        rm -rf dist build __pycache__ *.spec
    
    - name: Create executable (force clean)
      run: |
        pyinstaller --clean \
                   --name douyou_assistant \
                   --windowed \
                   --onedir \
                   --icon icon.ico \
                   --add-data src:src \
                   --add-data config:config \
                   --hidden-import PySide6.QtCore \
                   --hidden-import PySide6.QtWidgets \
                   --hidden-import PySide6.QtGui \
                   --hidden-import playwright \
                   --hidden-import playwright.sync_api \
                   --hidden-import src.worker \
                   --hidden-import src.account_manager \
                   --hidden-import src.downloader \
                   --hidden-import src.uploader \
                   --hidden-import requests \
                   --hidden-import rich \
                   --hidden-import browser_cookie3 \
                   gui_main.py

    - name: Create version info
      run: |
        echo "Version: ${{ github.event.inputs.version || github.ref_name }}" > version.txt
        echo "Build Date: $(date)" >> version.txt
        echo "Platform: ${{ matrix.platform }}" >> version.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: douyou_assistant-${{ matrix.platform }}
        path: |
          dist/douyou_assistant${{ matrix.ext }}
          version.txt
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Display structure of downloaded files
      run: ls -la ./artifacts/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/douyou_assistant-windows/douyou_assistant.exe
          ./artifacts/douyou_assistant-macos/douyou_assistant
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}